import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {OgreGraph} from '@dotinc/ogre-react'
import {Repository, RepositoryObject} from '@dotinc/ogre'
import {useEffect, useState} from 'react'

interface someClass {
  name: string
  description: string
}

const Home: NextPage = () => {
  const [repository, setRepository] = useState<RepositoryObject<someClass> | undefined>(undefined)
  useEffect(() => {
    if (!repository) {
      setupRepo()
    }
  }, [])

  const setupRepo = async () => {
    let author = 'author <author@email.info>'
    const r = new Repository<someClass>({description: '', name: ''}, {})
    r.data.name = 'new name'
    r.data.description = 'first description'
    await r.commit('initial commit', author)

    r.checkout('description', true)
    r.data.description = 'some longer different description'
    await r.commit('change desc', author)

    r.data.description = 'correct mistake made in prev description'
    await r.commit('fix desc', author)

    r.createBranch('another_branch')

    r.data.description = 'yet another correction'
    await r.commit('typo fix', author)

    r.checkout('main')
    r.merge('description')

    setRepository(r)
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {repository ? <OgreGraph repository={repository} /> : null}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
